/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:Y.K90CEK011YS-2E710
 * Manual Code: 26123634481
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0xBE9
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 56504116

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "wJnuWkQFV5ODHZz86ysvrNEr04XemPZTt7rOIyotdzUEP4h6YjwRMKu4KCRl6B3g/C" \
    "WspsI9ZRAiFffZRNEHd7iig0XYfnT4Mvo1pRzs3QOW18qm1FnVOI9UXtJUfILgFQ=="
