/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:Y.K9042C00G2CR74400
 * Manual Code: 14781903130
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0x620
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 5143243

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "vLRHDfWeZM8Zt7CWhmUTRW797sgM6ogJjmQMU7ot76EEX8GM2BIASvAFndrU90LrWi" \
    "gsajaJvXeV06ge3M82i7PiYTpS6capBTVM35MCVncEPK5lwWBeTUKatnCyNhS7Tw=="

/* Firmware Configuration ID (4-bit, 0-15)
 * Displayed as binary via LED during factory reset:
 * White = 1, Red = 0, MSB first, repeated 5 times
 */
#define FIRMWARE_CONFIG_ID 2
