/*
 * Auto-generated Matter Pairing Configuration
 * Generated by: scripts/generate_pairing_config.py
 *
 * QR Code:     MT:Y.K90S0.03FUE63YF00
 * Manual Code: 12928612087
 *
 * To regenerate: make generate-pairing
 */

#pragma once

/* Commissioning Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0x5DB
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 19804774

/* SPAKE2+ Parameters */
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_ITERATION_COUNT 1000
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_SALT "U1BBS0UyUCBLZXkgU2FsdA=="
#define CHIP_DEVICE_CONFIG_USE_TEST_SPAKE2P_VERIFIER \
    "CtUlmpJWQCsZfJKPrhuwJszHWAJ86wx1RrmAXtjWiS8EYYUpZSJhjg8I/1F4fdbkRJ" \
    "z6UZGmKzhvzNqPqk+HpwScHxqrgxGtPJBkfLw1pIcaRCq1g8kDv1CbqsjOKlvE+A=="
